# Generated by Django 6.1 on 2026-08-14 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('verse', 'Bible verse'), ('devotion', 'Devotion'), ('prayer', 'Prayer'), ('hymn', 'Hymn'), ('dictionary_term', 'Dictionary term')], max_length=20)),
                ('content_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'content_id'), name='uniq_user_content')],
            },
        ),
    ]
