import { Ionicons } from "@expo/vector-icons"
import { useEffect, useState } from "react"
import { Alert, Image, Pressable, StyleSheet, Switch, Text, View } from "react-native"
import { Stack, useRouter } from "expo-router"
import { useTranslation } from "react-i18next"
import { AppHeader } from "../src/components/AppHeader"
import { Screen } from "../src/components/Screen"
import { useProfile } from "../src/hooks/useProfile"
import { usePremium } from "../src/subscription/usePremium"
import { logout } from "../src/api/auth"
import { setLanguage } from "../src/i18n"
import { useTheme } from "../src/theme/useTheme"
export default function ProfileScreen() {
 const { t, i18n } = useTranslation(); const { colors, spacing, radius, type, isDark } = useTheme(); const router = useRouter(); const { user, loading } = useProfile(); const { isPremium } = usePremium(); const [notifications, setNotifications] = useState(true)
 useEffect(() => { if (!loading && !user) router.replace("/auth/login") }, [loading, user, router])
 if (!user) return <Screen header={<><Stack.Screen options={{ headerShown: false }} /><AppHeader title={t("tabs.profile")} /></>} />
 return <Screen scroll header={<><Stack.Screen options={{ headerShown: false }} /><AppHeader eyebrow="Your space" title={t("tabs.profile")} /></>}>
  <View style={styles.identity}><View style={[styles.avatar, { backgroundColor: colors.accentSoft, borderRadius: radius.full }]}>{user.profile_picture_url ? <Image source={{ uri: user.profile_picture_url }} style={styles.avatarImage} /> : <Text style={[type.title, { color: colors.accent }]}>{user.full_name?.charAt(0) ?? "U"}</Text>}</View><Text style={[type.title, { color: colors.text, marginTop: 12 }]}>{user.full_name}</Text><Text style={[type.caption, { color: colors.textMuted, marginTop: 3 }]}>{user.email || user.phone_number}</Text>{isPremium && <Text style={[type.overline, { color: colors.success, marginTop: 10 }]}>MEMBERSHIP ACTIVE</Text>}</View>
  {!isPremium && <Pressable onPress={() => router.push("/subscription")} style={[styles.premium, { backgroundColor: colors.primary, borderRadius: radius.md, marginTop: spacing.lg }]}><View style={{ flex: 1 }}><Text style={[type.overline, { color: colors.accent }]}>GO DEEPER</Text><Text style={[type.heading, { color: colors.primaryForeground, marginTop: 4 }]}>Make more room for faith</Text></View><Ionicons name="arrow-forward" size={19} color={colors.primaryForeground} /></Pressable>}
  <Text style={[type.overline, { color: colors.accent, marginTop: spacing.xl }]}>PREFERENCES</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, marginTop: spacing.sm }]}><Row icon="language-outline" label={t("settings.language")} value={i18n.language === "en" ? "English" : "Swahili"} colors={colors} onPress={() => setLanguage(i18n.language === "en" ? "sw" : "en")} /><Row icon="notifications-outline" label={t("settings.notifications")} colors={colors} right={<Switch value={notifications} onValueChange={setNotifications} trackColor={{ true: colors.accent, false: colors.border }} />} /><Row icon="moon-outline" label={t("settings.theme")} value={isDark ? "Dark" : "Light"} colors={colors} /></View>
  <Text style={[type.overline, { color: colors.accent, marginTop: spacing.xl }]}>ACCOUNT & APP</Text><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, marginTop: spacing.sm }]}><Row icon="card-outline" label={t("settings.subscription")} colors={colors} onPress={() => router.push("/subscription")} /><Row icon="information-circle-outline" label="About M-Kristo" value="Version 1.0.0" colors={colors} /><Row icon="log-out-outline" label={t("settings.logout")} colors={colors} onPress={async () => { await logout(); Alert.alert(t("settings.logout"), t("common.close")) }} /></View>
 </Screen>
}
function Row({ icon, label, value, right, colors, onPress }: { icon: keyof typeof Ionicons.glyphMap; label: string; value?: string; right?: React.ReactNode; colors: ReturnType<typeof useTheme>["colors"]; onPress?: () => void }) { return <Pressable onPress={onPress} disabled={!onPress && !right} style={styles.row}><View style={[styles.rowIcon, { backgroundColor: colors.surfaceMuted, borderRadius: 8 }]}><Ionicons name={icon} size={18} color={colors.accent} /></View><Text style={[styles.rowLabel, { color: colors.text }]}>{label}</Text>{value && <Text style={[type.caption, { color: colors.textMuted }]}>{value}</Text>}{right}</Pressable> }
const type = { caption: { fontSize: 12 } }
const styles = StyleSheet.create({ identity: { alignItems: "center" }, avatar: { width: 76, height: 76, alignItems: "center", justifyContent: "center" }, avatarImage: { width: "100%", height: "100%", borderRadius: 999 }, premium: { padding: 16, flexDirection: "row", alignItems: "center" }, group: { borderWidth: 1, overflow: "hidden" }, row: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: "rgba(128,118,100,0.18)" }, rowIcon: { width: 32, height: 32, alignItems: "center", justifyContent: "center" }, rowLabel: { flex: 1, fontSize: 15, fontWeight: "600" } })
