import { Ionicons } from "@expo/vector-icons"
import { useRouter } from "expo-router"
import { useEffect, useState } from "react"
import { useTranslation } from "react-i18next"
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from "react-native"
import { getLocalBooks, getVerseOfTheDay, type Book, type VerseOfDay } from "../../src/api/bible"
import { AppHeader } from "../../src/components/AppHeader"
import { Screen } from "../../src/components/Screen"
import { useTheme } from "../../src/theme/useTheme"

export default function TodayScreen() {
  const { t, i18n } = useTranslation(); const { colors, spacing, radius, type } = useTheme(); const router = useRouter(); const [verse, setVerse] = useState<VerseOfDay | null>(null); const [books, setBooks] = useState<Book[]>([]); const [loading, setLoading] = useState(true); const isEnglish = i18n.language === "en"
  useEffect(() => { Promise.all([getVerseOfTheDay(), getLocalBooks()]).then(([daily, localBooks]) => { setVerse(daily); setBooks(localBooks) }).finally(() => setLoading(false)) }, [])
  const text = verse && (isEnglish && verse.text_en ? verse.text_en : verse.text_sw); const reference = verse && (isEnglish && verse.reference_en ? verse.reference_en : verse.reference_sw)
  function openPassage() { const name = reference?.replace(/\s+\d+:.*$/, "").trim() ?? "Genesis"; const book = books.find((item) => item.name_en.toLowerCase() === name.toLowerCase() || item.name_sw.toLowerCase() === name.toLowerCase()); if (book) router.push({ pathname: "/bible/[bookId]", params: { bookId: book.id } }); else router.push("/bible") }
  const tasks = [{ icon: "book-outline" as const, label: isEnglish ? "Read today’s passage" : "Soma kifungu cha leo", onPress: openPassage }, { icon: "hand-left-outline" as const, label: isEnglish ? "Take a quiet minute to pray" : "Tenga dakika za kuomba", onPress: () => router.push("/prayers") }, { icon: "create-outline" as const, label: isEnglish ? "Write a reflection" : "Andika tafakari", onPress: () => router.push("/notes") }]
  return <Screen scroll header={<AppHeader title={t("tabs.today")} />}><View style={{ gap: spacing.sm }}><Text style={[type.overline, { color: colors.accent }]}>{t("home.verseOfDay")}</Text></View><View style={[styles.verseCard, { backgroundColor: colors.primary, borderRadius: radius.lg, marginTop: spacing.md }]}><View style={styles.verseTop}><Ionicons name="book-outline" size={18} color={colors.accent} /><Text style={[type.label, { color: colors.accent }]}>NENO LA LEO</Text></View>{loading ? <ActivityIndicator color={colors.accent} style={{ marginVertical: 58 }} /> : <><Text style={[type.scripture, styles.verseText, { color: colors.primaryForeground }]}>{text ? `“${text}”` : t("common.empty")}</Text><Text style={[type.label, { color: colors.accent, marginTop: spacing.md }]}>{reference}</Text><View style={styles.actions}><Pressable onPress={openPassage} style={[styles.action, { backgroundColor: colors.primaryForeground }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{isEnglish ? "READ PASSAGE" : "SOMA KIFUNGU"}</Text></Pressable></View></>}</View><View style={[styles.section, { marginTop: spacing.xl }]}><View style={styles.sectionHeader}><Text style={[type.title, { color: colors.text }]}>{isEnglish ? "Your rhythm" : "Ratiba yako"}</Text><Pressable onPress={() => router.push("/calendar")}><Text style={[type.label, { color: colors.accent }]}>{isEnglish ? "JOURNAL" : "SHAJARA"}</Text></Pressable></View><View style={[styles.taskCard, { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.md, marginTop: spacing.md }]}>{tasks.map((task) => <Pressable key={task.label} onPress={task.onPress} style={styles.task}><View style={[styles.taskIcon, { backgroundColor: colors.surfaceMuted }]}><Ionicons name={task.icon} size={17} color={colors.primary} /></View><Text style={[type.body, { color: colors.text, flex: 1 }]}>{task.label}</Text><Ionicons name="chevron-forward" size={16} color={colors.textFaint} /></Pressable>)}</View></View><Pressable onPress={() => router.push("/notes")} style={[styles.bibleRow, { borderColor: colors.border, marginTop: spacing.md }]}><Ionicons name="document-text-outline" size={20} color={colors.accent} /><Text style={[type.heading, { color: colors.text, flex: 1 }]}>{isEnglish ? "Reading notes" : "Kumbukumbu za usomaji"}</Text><Ionicons name="arrow-forward" size={19} color={colors.accent} /></Pressable></Screen>
}
const styles = StyleSheet.create({ verseCard: { padding: 20 }, verseTop: { flexDirection: "row", alignItems: "center", gap: 9 }, verseText: { marginTop: 34 }, actions: { flexDirection: "row", gap: 9, marginTop: 24 }, action: { flex: 1, alignItems: "center", justifyContent: "center", paddingVertical: 13, borderRadius: 6 }, sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, section: {}, taskCard: { borderWidth: 1, paddingHorizontal: 14 }, task: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(128,118,100,0.2)" }, taskIcon: { width: 30, height: 30, borderRadius: 15, alignItems: "center", justifyContent: "center" }, bibleRow: { flexDirection: "row", alignItems: "center", gap: 12, borderTopWidth: 1, borderBottomWidth: 1, paddingVertical: 18 } })
