# Generated by Django 6.1 on 2026-08-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('neno_la_leo', 'Neno la Leo'), ('tafakari', 'Tafakari'), ('somo', 'Somo')], max_length=20)),
                ('devotion_date', models.DateField()),
                ('title_sw', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body_sw', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('scripture_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'devotions',
                'ordering': ['-devotion_date'],
                'indexes': [models.Index(fields=['devotion_date'], name='devotions_devotio_a9794a_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'devotion_date'), name='uniq_type_date')],
            },
        ),
    ]
