# Generated by Django 6.1 on 2026-08-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True)),
                ('kind', models.CharField(choices=[('sala', 'Sala'), ('novena', 'Novena')], max_length=10)),
                ('is_premium', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'prayer categories',
                'db_table': 'prayer_categories',
                'ordering': ['kind', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title_sw', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('body_sw', models.TextField()),
                ('body_en', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='prayers.prayercategory')),
            ],
            options={
                'db_table': 'prayers',
                'ordering': ['category', 'order_index', 'day_number'],
                'indexes': [models.Index(fields=['category'], name='prayers_categor_1c2bdc_idx')],
            },
        ),
    ]
