# Generated by Django 6.1 on 2026-08-14 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('testament', models.CharField(choices=[('old', 'Old Testament'), ('new', 'New Testament')], max_length=3)),
                ('book_order', models.PositiveSmallIntegerField(unique=True)),
                ('chapter_count', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bible_books',
                'ordering': ['book_order'],
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse_number', models.PositiveSmallIntegerField()),
                ('text_sw', models.TextField()),
                ('text_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.biblebook')),
            ],
            options={
                'db_table': 'bible_verses',
                'ordering': ['book', 'chapter', 'verse_number'],
            },
        ),
        migrations.CreateModel(
            name='VerseOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateField(unique=True)),
                ('short_text_sw', models.TextField()),
                ('short_text_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='featured_days', to='bible.bibleverse')),
            ],
            options={
                'db_table': 'verse_of_the_day',
                'ordering': ['-display_date'],
            },
        ),
        migrations.AddIndex(
            model_name='bibleverse',
            index=models.Index(fields=['book', 'chapter'], name='bible_verse_book_id_992204_idx'),
        ),
        migrations.AddConstraint(
            model_name='bibleverse',
            constraint=models.UniqueConstraint(fields=('book', 'chapter', 'verse_number'), name='uniq_book_chapter_verse'),
        ),
    ]
