# Generated by Django 6.1 on 2026-08-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_sw', models.CharField(db_index=True, max_length=150)),
                ('term_en', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('definition_sw', models.TextField()),
                ('definition_en', models.TextField(blank=True, null=True)),
                ('related_scripture_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dictionary_terms',
                'ordering': ['term_sw'],
            },
        ),
    ]
